name: test_Django
on: [pull_request, push]
jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          envkey_SECRET_KEY: '123456abcdef'
          file_name: .env
          fail_on_empty: fals
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt
      - run: python manage.py test .