name: test_Django
on: [pull_request, push]
jobs:
  unit_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Create .env file
        run: |
            touch .env
            echo SECRET_KEY="123456abcdef" >> .env
            cat .env
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt
      - run: python manage.py test